load("@rules_java//java:defs.bzl", "java_binary")

java_library(
    name = "greeter",
    srcs = ["Greeting.java"],
    visibility = ["//src/main/java/com/bazel/java/demo/runner:__pkg__", "//:__pkg__"],
)